python src/classifier.py --config="bart-base_1"
python src/classifier.py --config="bart-base_2"
python src/classifier.py --config="bart-base_3"
python src/classifier.py --config="bert-large-uncased_1"
python src/classifier.py --config="bert-large-uncased_2"
python src/classifier.py --config="bert-large-uncased_3"
